### ISSUE TITLE
Variants does not work.

### ISSUE THREAD

**Issue by Giovanny-DS** [kalfheim/tailwind-filter-utilities#2]
hover and focus variants does not work.

**Comment by tomyates** [comment]
In the varients section of your tailwind config, add the variants you need such as:

```
filters: ['hover', 'group-hover'],
bgFilters: ['hover'],
```

**Comment by Giovanny-DS** [comment]
i did. uncomment this line but still doens't work
` variants: {
    // filters: ['hover'],
    // bgFilters: ['hover'],
  },`

**Comment by tomyates** [comment]
I added them to my project tailwind config file, I didn't edit the module directly.

**Comment by Giovanny-DS** [comment]
well i tried both. first i did on my project. then i tried on the module. but didn't worked anyways.

**Comment by tomyates** [comment]
Did you recompile your tailwind CSS after?

**Comment by kalfheim** [comment]
Closing for now.

Thanks @tomyates for replying! 😄
